parameters:
    stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe.webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'

services:
    Stripe\StripeClient:
        arguments:
            - '%stripe.secret_key%' 